delete from LinuxCommandPageRelation;
delete from LinuxCommandOP;
delete from LinuxCommandPage;
delete from linuxcommandandfilerelation;
delete from linuxfileinfo;
delete from linuxfilepagerelation;
delete from linuxfiletabledata;
delete from linuxfiletableheader;
delete from linuxfile;
delete from LinuxCommandOtherChunkTableData;
delete from LinuxCommandOtherChunkTableHeader;
delete from LinuxCommandOtherChunk;
delete from LinuxCommand;
delete from LinuxCommandCurrentCID;
delete from LinuxCommandCurrentPID;
delete from LinuxFileCurrentFID;
insert into LinuxCommandCurrentCID values(1);
insert into LinuxCommandCurrentPID values(1);
insert into LinuxFileCurrentFID values(1);
select setval ('linuxcommandn_cid_seq',1);
select setval ('linuxcommandpagen_pid_seq',1);
select setval ('linuxfile_fid_seq',1);
